### PR TITLE
Various tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**
Most important are the package.json and the `maxmin` call patches.

https://github.com/dtrunk90/grunt-xmlmin/pull/2/files?w=1

### CODE REVIEW

**Comment by dtrunk90** [comment]
Thanks for your efforts.
As per API it should be `maxmin(max, min, useGzip)`: https://www.npmjs.com/package/maxmin
Is their API wrong?

**Comment by XhmikosR** [comment]
The API is right. You called `min, max` instead of `max, min`. As you can see from the results now it makes sense :p Previously, all minified files were bigger.

**Comment by dtrunk90** [comment]
Oh, lol. Right. I guess I need glasses. :-/

**Comment by XhmikosR** [comment]
Hehe, happens sometimes :P

Can I expect a 0.1.4 release?

**Comment by dtrunk90** [comment]
Yep. ~10min.

**Comment by XhmikosR** [comment]
Awesome, thanks!

**Comment by dtrunk90** [comment]
Done.

**Pull request merged**
