### PR TITLE
Minor cleanup.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by dtrunk90** [comment]
Is there a reason why you removed the contents from `.npmignore` file?

**Comment by XhmikosR** [comment]
It's redundant since we specify the files in package.json.

**Comment by dtrunk90** [comment]
Thanks for your efforts

**Comment by XhmikosR** [comment]
Thanks. Will you make a new release?

**Comment by dtrunk90** [comment]
Done

**Pull request merged**
